### ISSUE TITLE
Missed fix in https://www.swig.org/tutorial.html

### ISSUE THREAD

**Issue by davecb** [swig/www#18]
In the tutorial, the gcc command line uses "-I/usr/local/include". 

Instead, on Ubuntu 24.04.1 LTS  after "sudo apt install tcl8.6-dev tk8.6-dev", the needed include option is  "-I/usr/include/tcl" 

I also had to guess the version of the development files (;-))

--dave c-b, pretending to be a new user
["we are the occasional user", as attributed to Dennis Ritchie]

**Comment by wsfulton** [comment]
Hi @davecb, I've updated the page to show for Ubuntu instead of 'Linux', see swig/www@b42c6f86d93cf1b38329d3a975d4fd915f0ccfbe. The tutorial is not wrong for tcl installed in /usr/local and the tutorial example is never going to be valid for every operating system and version thereof! The tutorial has links to [SWIG Wiki Shared Libraries](https://github.com/swig/swig/wiki/FAQ#shared-libraries) which is for users to contribute other useful variations. Patches to make this clearer are welcome.
